### ISSUE TITLE
About ideal ranking

### ISSUE THREAD

**Issue by Aliezzz** [shuaiOKshuai/IPE#3]
Hi, I've read your paper, it's a great job.

btw, I want to know how do you set ideal ranking for each test query user?  

Do you use the same ideal ranking with ProxEmbed?  https://github.com/vwz/ProxEmbed 
In the paper of ProxEmbed, it says "other nodes that are the same class with qi are ranked higher than those with a different class or unknown label". 

If we seek for the relationship of "family", and use "classmate" as a negative label in training, 
will the ideal rank be "family > unknown label > classmate"?

1) how do we set the rank of unknow label? Do the nodes that have more same attributes with the query node will rank higher?
2) how do we set the rank of nodes that have the same class?

In addition, in evaluation, does the model predict the ranking of all users for each test query node and compare the top 10 nodes against the ideal ranking?

thanks!

**Comment by shuaiOKshuai** [comment]
> Hi, I've read your paper, it's a great job.
> 
> btw, I want to know how do you set ideal ranking for each test query user?
> 
> Do you use the same ideal ranking with ProxEmbed? https://github.com/vwz/ProxEmbed
> In the paper of ProxEmbed, it says "other nodes that are the same class with qi are ranked higher than those with a different class or unknown label".
> 
> If we seek for the relationship of "family", and use "classmate" as a negative label in training,
> will the ideal rank be "family > unknown label > classmate"?
> 
> 1. how do we set the rank of unknow label? Do the nodes that have more same attributes with the query node will rank higher?
> 2. how do we set the rank of nodes that have the same class?
> 
> In addition, in evaluation, does the model predict the ranking of all users for each test query node and compare the top 10 nodes against the ideal ranking?
> 
> thanks!

Hi, thanks for your interest.

1. Yes, we use the same ideal ranking with ProxEmbed. 

2. If you seek for the relationship of "family", then all the other relationships (including "classmate" relation and unknown label relation) would serve as the negative labels.
Now the ideal rank is NOT "family > unknown label > classmate", but it should be "family > unknown label & classmate". Namely, all the rest relations (including unknow labels and classmate relations) are the negative labels.

4. how do we set the rank of unknow label? Do the nodes that have more same attributes with the query node will rank higher?
Actually, after we achieve the ground-truth relation (i.e., the family relation), to generate all the negative labels, we randomly sample the rest nodes to serve as the negative labels. In other words, the negative samples include the unknown label, as well as the "classmate" relation. Particular, we regard these negative samples have the identical ranking score, without considering their attributes are more or less with the query node.

5. how do we set the rank of nodes that have the same class?
For example, suppose we have a candidate list: a, b, c, d, e. In this list, only b and d are the positive samples (b and d have the same ranking score), while the rest three are negative samples. We use ranking metric for evaluation. Actually, if you rank b and d in the first two positions, then you would achieve the highest score. For example, rank "b, d, a, e, c", rank "b, d, c, e, a" and rank "d, b, e, c, a" have the same scores, and all these three scores are the highest scores. Here, nodes "a, c, e" may belong to different relations, but we don't need to consider, and all of them are negative samples and have the same ranking score.

6. In addition, in evaluation, does the model predict the ranking of all users for each test query node and compare the top 10 nodes against the ideal ranking?
Actually, in our test data, each query has the following format:
q c1, c2, c3,..., cn
where q is the query node, and the rest c1,...,cn are the candidates (for example, n=30). In these n candidates, there are m (m<n) positive samples (e.g., m=10), and n-m negative samples. We only need to calculate the scores for these n samples (not all nodes in this graph), and compare the top m samples with the ideal rank.

Hope these could help you.

**Comment by Aliezzz** [comment]
Thanks for your replay,

For example, suppose we have a candidate list: a, b, c, d, e. In this list, only b and d are the positive samples (b and d have the same ranking score), while the rest three are negative samples. We use ranking metric for evaluation. Actually, if you rank b and d in the first two positions, then you would achieve the highest score. For example, rank "b, d, a, e, c", rank "b, d, c, e, a" and rank "d, b, e, c, a" have the same scores, and all these three scores are the highest scores. Here, nodes "a, c, e" may belong to different relations, but we don't need to consider, and all of them are negative samples and have the same ranking score.

In my understanding, suppose we have a candidate list: a, b, c, d, e, only b and d are positive samples. We mark the positive sample as 1 and mark the negative as 0. List of the candidate label is "0, 1, 0, 1, 0", and list of the ideal ranking label is "1, 1, 0, 0, 0". We just need to compare the list of the prediction label with "1, 1, 0, 0, 0", right?

Thanks!

**Comment by shuaiOKshuai** [comment]
> Thanks for your replay,
> 
> For example, suppose we have a candidate list: a, b, c, d, e. In this list, only b and d are the positive samples (b and d have the same ranking score), while the rest three are negative samples. We use ranking metric for evaluation. Actually, if you rank b and d in the first two positions, then you would achieve the highest score. For example, rank "b, d, a, e, c", rank "b, d, c, e, a" and rank "d, b, e, c, a" have the same scores, and all these three scores are the highest scores. Here, nodes "a, c, e" may belong to different relations, but we don't need to consider, and all of them are negative samples and have the same ranking score.
> 
> In my understanding, suppose we have a candidate list: a, b, c, d, e, only b and d are positive samples. We mark the positive sample as 1 and mark the negative as 0. List of the candidate label is "0, 1, 0, 1, 0", and list of the ideal ranking label is "1, 1, 0, 0, 0". We just need to compare the list of the prediction label with "1, 1, 0, 0, 0", right?
> 
> Thanks!

Yes, that's it.

**Comment by Aliezzz** [comment]
Ok, Thanks!  :)
