### ISSUE TITLE
What does 'D:/test/link-prediction/saveFile' in dataProcessTools.py refer to ?

### ISSUE THREAD

**Issue by SigProcess** [shuaiOKshuai/IPE#4]
Hi,
What does the file 'D:/test/link-prediction/saveFile' which is saved in the variable dependencySaveFile in the python file dataProcessTools.py refer to?
 Can you please tell me the format of that file? Thanks.

**Comment by SigProcess** [comment]
I believe this file contains sub-paths extracted from the graph using random walk. Is there a code to extract these subpaths?

**Comment by shuaiOKshuai** [comment]
> Hi, What does the file 'ç' which is saved in the variable dependencySaveFile in the python file dataProcessTools.py refer to? Can you please tell me the format of that file? Thanks.

Hi, sorry for the delayed response.
This file (D:/test/link-prediction/saveFile) is just used for code test. In this main function (dataProcessTools.py), I tested the code for validation. Sorry for the confusion.

The following is the example data in this file (D:/test/link-prediction/saveFile), in which each row records the dependency in building the interactive paths. You can refer to file prepareSubpathsToInteractiveSeqs.py to achieve these interactive paths. However, I cannot remember the exact meaning of the format.

5-9&5-0 3-6 7-7 2-8 9-14 #5-1 2-9 8-10 3-11 9-12 #5-2 11-3 15-4 13-5 9-13 #&0:9<-1:3 0:9<-2:13 0:2<-1:5 1:9<-0:2 1:9<-2:13 1:2<-0:7 1:3<-0:5 2:9<-0:2 2:9<-1:3 
5-19&5-0 4-4 6-5 8-6 10-7 19-13 #5-1 13-2 8-8 19-14 #5-3 6-9 12-10 4-11 19-12 #&0:8<-1:13 0:19<-1:8 0:19<-2:4 0:6<-2:5 1:8<-0:6 1:19<-0:10 1:19<-2:4 2:19<-0:10 2:19<-1:8 2:4<-0:5 2:6<-0:4

**Comment by shuaiOKshuai** [comment]
In particular, please read the REAMDE file before running the code, since this file also indicates that the readers should run file prepareSubpathsToInteractiveSeqs.py first before running the model (this file can prepare the interactive paths). Thank you.

**Comment by SigProcess** [comment]
Thank you very much for your answer. If I understand correctly, these are the interactive paths obtained from the extracted sub-paths from the graph. These sub-paths are obtained using a random walk. If possible, could you tell me how I can create those sub-paths? Is there a code for it? Thanks again.

**Comment by shuaiOKshuai** [comment]
> Thank you very much for your answer. If I understand correctly, these are the interactive paths obtained from the extracted sub-paths from the graph. These sub-paths are obtained using a random walk. If possible, could you tell me how I can create those sub-paths? Is there a code for it? Thanks again.

Sorry for the confusion.
We also provided the sub-path generation code in one of our previous projects. Please see our project ProxEmbed (https://github.com/shuaiOKshuai/ProxEmbed; in the code, either symmetric or asymmetric is OK; we utilize the java code to prepare the data). In particular, in file https://github.com/shuaiOKshuai/ProxEmbed/blob/master/code/asymmetric/java%20-%20prepare%20data%20for%20model/Main.java, we conduct random walk to sample paths in line 23, and generate the sub-paths from the sampled paths in line 32.

Hope it can help you. Thank you.

**Comment by SigProcess** [comment]
That answers all my questions. Thank you very much!
