### ISSUE TITLE
Getting index mismatch-theano error

### ISSUE THREAD

**Issue by SigProcess** [shuaiOKshuai/IPE#5]
Hi,

I was able to generate the nodesFeatures and subpaths file using the Java code given in the ProxEmbed repository. However, the TypesFeatures files was not generated, so I created it by understanding how it is being read in the code. I basically used LinkedIn dataset corresponding to 'school' and thus used 4 datatypes and one-hot encoded them as suggested in the paper:

4 4
0 1.0 0.0 0.0 0.0 
1 0.0 1.0 0.0 0.0 
2 0.0 0.0 1.0 0.0 
3 0.0 0.0 0.0 1.0 

 However, I am now getting a dimension mismatch error, raised by theano. As per my understanding, it is suggesting a dimension mismatch between the nodes features (generated by the Java code )  and the types features. The nodesFeatures file has the follwing contents:

13 10
0 1.0 0.0 0.0 0.0 1.3862943611198906 0.6931471805599453 0.6931471805599453 0.6931471805599453 0.0 1.0986122886681096
1 0.0 1.0 0.0 0.0 1.0986122886681098 1.0986122886681098 0.0 0.0 0.0 0.0
2 0.0 0.0 1.0 0.0 1.6094379124341003 1.6094379124341003 0.0 0.0 0.0 0.0
3 1.0 0.0 0.0 0.0 1.6094379124341003 1.0986122886681098 0.6931471805599453 0.6931471805599453 0.0 1.0397207708399179
4 1.0 0.0 0.0 0.0 1.3862943611198906 0.6931471805599453 0.0 0.6931471805599453 0.6931471805599453 1.0986122886681096
5 0.0 0.0 0.0 1.0 1.0986122886681098 1.0986122886681098 0.0 0.0 0.0 0.0
6 1.0 0.0 0.0 0.0 1.791759469228055 1.0986122886681098 0.0 0.6931471805599453 1.0986122886681098 1.0549201679861442
7 1.0 0.0 0.0 0.0 1.3862943611198906 1.0986122886681098 0.0 0.0 0.6931471805599453 0.6365141682948128
8 0.0 0.0 0.0 1.0 1.0986122886681098 1.0986122886681098 0.0 0.0 0.0 0.0
9 1.0 0.0 0.0 0.0 1.6094379124341003 0.6931471805599453 0.6931471805599453 0.0 1.0986122886681098 1.0397207708399179
10 0.0 0.0 0.0 1.0 1.3862943611198906 1.3862943611198906 0.0 0.0 0.0 0.0
11 0.0 1.0 0.0 0.0 1.0986122886681098 1.0986122886681098 0.0 0.0 0.0 0.0
12 1.0 0.0 0.0 0.0 1.3862943611198906 0.6931471805599453 0.6931471805599453 0.0 0.6931471805599453 1.0986122886681096

I spent a lot of time figuring out what could be wrong, but have not been able to debug it. I am attaching the error trace here. The fact that it says "IndexError: index 12 is out of bounds for axis 0 with size 4" makes me think it is due to a mismatch between the size of the nodes features (total 13 in number) and types features (total 4 in number). Kindly help me know what is the issue here. Thanks.

Here is the error trace:

WARNING (theano.configdefaults): install mkl with `conda install mkl-service`: No module named 'mkl'
WARNING (theano.tensor.blas): Using NumPy C-API based implementation for BLAS functions.
Start to train the model ...... time == 2023-01-24 06:45:17
init shared Variables......
Generate models ......
Generate gradients ......
Using Adadelta to generate functions ......
f_update <theano.compile.function_module.Function object at 0x7fb610048d10>
Start training models ......
start time == 2023-01-24 06:46:07
Traceback (most recent call last):
  File "scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform
IndexError: index 12 is out of bounds for axis 0 with size 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform
  File "/opt/conda/lib/python3.7/site-packages/theano/scan_module/scan_op.py", line 963, in rval
    r = p(n, [x[0] for x in i], o)
  File "/opt/conda/lib/python3.7/site-packages/theano/scan_module/scan_op.py", line 952, in p
    self, node)
  File "scan_perform.pyx", line 405, in theano.scan_module.scan_perform.perform
  File "/opt/conda/lib/python3.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/opt/conda/lib/python3.7/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform
IndexError: index 12 is out of bounds for axis 0 with size 4
Apply node that caused the error: AdvancedSubtensor1(typesEmbeddings_copy, Subtensor{int64, :int64:}.0)
Toposort index: 15
Inputs types: [TensorType(float64, matrix), TensorType(int64, vector)]
Inputs shapes: [(4, 4), (6,)]
Inputs strides: [(32, 8), (8,)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[forall_inplace,cpu,scan_fn}(Elemwise{Maximum}[(0, 0)].0, Subtensor{int64:int64:int8}.0, IncSubtensor{InplaceSet;:int64:}.0, W_z_copy, U_z_copy, type_eta_copy, b_z_copy, W_h_copy, U_h_copy, W_r_copy, U_r_copy, b_r_copy, b_h_copy, AdvancedSubtensor1.0, Subtensor{int64, :int64:, :int64:}.0, Subtensor{int64, :int64:, :int64:}.0, InplaceDimShuffle{0,x}.0, AdvancedSubtensor1.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "/opt/conda/lib/python3.7/site-packages/theano/scan_module/scan_op.py", line 963, in rval
    r = p(n, [x[0] for x in i], o)
  File "/opt/conda/lib/python3.7/site-packages/theano/scan_module/scan_op.py", line 952, in p
    self, node)
  File "scan_perform.pyx", line 405, in theano.scan_module.scan_perform.perform
  File "/opt/conda/lib/python3.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/opt/conda/lib/python3.7/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform
  File "/opt/conda/lib/python3.7/site-packages/theano/scan_module/scan_op.py", line 963, in rval
    r = p(n, [x[0] for x in i], o)
  File "/opt/conda/lib/python3.7/site-packages/theano/scan_module/scan_op.py", line 952, in p
    self, node)
  File "scan_perform.pyx", line 405, in theano.scan_module.scan_perform.perform
  File "/opt/conda/lib/python3.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/opt/conda/lib/python3.7/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform
IndexError: index 12 is out of bounds for axis 0 with size 4
Apply node that caused the error: AdvancedSubtensor1(typesEmbeddings_copy, Subtensor{int64, :int64:}.0)
Toposort index: 15
Inputs types: [TensorType(float64, matrix), TensorType(int64, vector)]
Inputs shapes: [(4, 4), (6,)]
Inputs strides: [(32, 8), (8,)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[forall_inplace,cpu,scan_fn}(Elemwise{Maximum}[(0, 0)].0, Subtensor{int64:int64:int8}.0, IncSubtensor{InplaceSet;:int64:}.0, W_z_copy, U_z_copy, type_eta_copy, b_z_copy, W_h_copy, U_h_copy, W_r_copy, U_r_copy, b_r_copy, b_h_copy, AdvancedSubtensor1.0, Subtensor{int64, :int64:, :int64:}.0, Subtensor{int64, :int64:, :int64:}.0, InplaceDimShuffle{0,x}.0, AdvancedSubtensor1.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
Apply node that caused the error: for{cpu,scan_fn}(Elemwise{Composite{maximum((i0 - i1), i2)}}.0, Subtensor{int64:int64:int8}.0, Elemwise{Composite{maximum((i0 - i1), i2)}}.0, W_z_copy0, U_z_copy0, type_eta_copy0, b_z_copy0, W_h_copy0, U_h_copy0, W_r_copy0, U_r_copy0, b_r_copy0, b_h_copy0, sequences_matrix_copy0, sequencesLen_vector_copy0, wordsEmbeddings_copy0, dependency_matrix_copy0, discountForEachNode_matrix_copy0, dependWeight_matrix_copy0, typesEmbeddings_copy0, discountSeq_matrix_copy0)
Toposort index: 129
Inputs types: [TensorType(int64, scalar), TensorType(int64, vector), TensorType(int64, scalar), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, vector), TensorType(float64, vector), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, vector), TensorType(float64, vector), TensorType(int64, matrix), TensorType(int64, vector), TensorType(float64, matrix), TensorType(float64, 3D), TensorType(float64, matrix), TensorType(float64, 3D), TensorType(float64, matrix), TensorType(float64, matrix)]
Inputs shapes: [(), (3,), (), (9, 9), (9, 9), (4,), (9,), (9, 9), (9, 9), (9, 9), (9, 9), (9,), (9,), (36, 11), (36,), (13, 10), (36, 11, 11), (36, 11), (36, 11, 11), (4, 4), (36, 11)]
Inputs strides: [(), (8,), (), (72, 8), (72, 8), (8,), (8,), (72, 8), (72, 8), (72, 8), (72, 8), (8,), (8,), (88, 8), (8,), (80, 8), (968, 88, 8), (88, 8), (968, 88, 8), (32, 8), (88, 8)]
Inputs values: [array(3), array([0, 1, 2]), array(3), 'not shown', 'not shown', array([ 0.27957155,  0.17552981,  0.27293447, -0.19001233]), 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown']
Outputs clients: [[Reduce{maximum}{0}(for{cpu,scan_fn}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/jupyter/experiments/Tns/IPE/IPESerial/experimentForOneFileByParams.py", line 100, in <module>
    decay)
  File "/home/jupyter/experiments/Tns/IPE/IPESerial/interactiveGRU.py", line 239, in interactiveGRUTraining
    cost=f_grad_shared(trainingParis_data, sequences_matrix_data, dependency_matrix_data, dependWeight_matrix_data, sequencesLen_vector_data, discountSeq_matrix_data, discountForEachNode_matrix_data, wordsEmbeddings, typesEmbeddings)
  File "/opt/conda/lib/python3.7/site-packages/theano/compile/function_module.py", line 917, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/opt/conda/lib/python3.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/opt/conda/lib/python3.7/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "/opt/conda/lib/python3.7/site-packages/theano/compile/function_module.py", line 903, in __call__
    self.fn() if output_subset is None else\
  File "/opt/conda/lib/python3.7/site-packages/theano/scan_module/scan_op.py", line 963, in rval
    r = p(n, [x[0] for x in i], o)
  File "/opt/conda/lib/python3.7/site-packages/theano/scan_module/scan_op.py", line 952, in p
    self, node)
  File "scan_perform.pyx", line 405, in theano.scan_module.scan_perform.perform
  File "/opt/conda/lib/python3.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/opt/conda/lib/python3.7/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform
  File "/opt/conda/lib/python3.7/site-packages/theano/scan_module/scan_op.py", line 963, in rval
    r = p(n, [x[0] for x in i], o)
  File "/opt/conda/lib/python3.7/site-packages/theano/scan_module/scan_op.py", line 952, in p
    self, node)
  File "scan_perform.pyx", line 405, in theano.scan_module.scan_perform.perform
  File "/opt/conda/lib/python3.7/site-packages/theano/gof/link.py", line 325, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/opt/conda/lib/python3.7/site-packages/six.py", line 718, in reraise
    raise value.with_traceback(tb)
  File "scan_perform.pyx", line 397, in theano.scan_module.scan_perform.perform
IndexError: index 12 is out of bounds for axis 0 with size 4
Apply node that caused the error: AdvancedSubtensor1(typesEmbeddings_copy, Subtensor{int64, :int64:}.0)
Toposort index: 15
Inputs types: [TensorType(float64, matrix), TensorType(int64, vector)]
Inputs shapes: [(4, 4), (6,)]
Inputs strides: [(32, 8), (8,)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[forall_inplace,cpu,scan_fn}(Elemwise{Maximum}[(0, 0)].0, Subtensor{int64:int64:int8}.0, IncSubtensor{InplaceSet;:int64:}.0, W_z_copy, U_z_copy, type_eta_copy, b_z_copy, W_h_copy, U_h_copy, W_r_copy, U_r_copy, b_r_copy, b_h_copy, AdvancedSubtensor1.0, Subtensor{int64, :int64:, :int64:}.0, Subtensor{int64, :int64:, :int64:}.0, InplaceDimShuffle{0,x}.0, AdvancedSubtensor1.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
Apply node that caused the error: for{cpu,scan_fn}(Elemwise{Composite{maximum((i0 - i1), i2)}}.0, Subtensor{int64:int64:int8}.0, Elemwise{Composite{maximum((i0 - i1), i2)}}.0, W_z_copy0, U_z_copy0, type_eta_copy0, b_z_copy0, W_h_copy0, U_h_copy0, W_r_copy0, U_r_copy0, b_r_copy0, b_h_copy0, sequences_matrix_copy0, sequencesLen_vector_copy0, wordsEmbeddings_copy0, dependency_matrix_copy0, discountForEachNode_matrix_copy0, dependWeight_matrix_copy0, typesEmbeddings_copy0, discountSeq_matrix_copy0)
Toposort index: 129
Inputs types: [TensorType(int64, scalar), TensorType(int64, vector), TensorType(int64, scalar), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, vector), TensorType(float64, vector), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, vector), TensorType(float64, vector), TensorType(int64, matrix), TensorType(int64, vector), TensorType(float64, matrix), TensorType(float64, 3D), TensorType(float64, matrix), TensorType(float64, 3D), TensorType(float64, matrix), TensorType(float64, matrix)]
Inputs shapes: [(), (3,), (), (9, 9), (9, 9), (4,), (9,), (9, 9), (9, 9), (9, 9), (9, 9), (9,), (9,), (36, 11), (36,), (13, 10), (36, 11, 11), (36, 11), (36, 11, 11), (4, 4), (36, 11)]
Inputs strides: [(), (8,), (), (72, 8), (72, 8), (8,), (8,), (72, 8), (72, 8), (72, 8), (72, 8), (8,), (8,), (88, 8), (8,), (80, 8), (968, 88, 8), (88, 8), (968, 88, 8), (32, 8), (88, 8)]
Inputs values: [array(3), array([0, 1, 2]), array(3), 'not shown', 'not shown', array([ 0.27957155,  0.17552981,  0.27293447, -0.19001233]), 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown']
Outputs clients: [[Reduce{maximum}{0}(for{cpu,scan_fn}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
Apply node that caused the error: forall_inplace,cpu,scan_fn&grad_of_scan_fn}(Elemwise{maximum,no_inplace}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int64}.0, Subtensor{::int64}.0, IncSubtensor{InplaceSet;:int64:}.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, Alloc.0, W_z01, U_z01, type_eta01, b_z01, W_h01, U_h01, W_r01, U_r01, b_r01, b_h01, w01, sequences_matrix01, sequencesLen_vector01, wordsEmbeddings01, dependency_matrix01, discountForEachNode_matrix01, dependWeight_matrix01, typesEmbeddings01, discountSeq_matrix01, Shape_i{1}.0, Shape_i{0}.0, Shape_i{1}.0, Shape_i{0}.0, Shape_i{2}.0, Shape_i{1}.0, Shape_i{0}.0, Shape_i{1}.0, Shape_i{0}.0, Shape_i{2}.0, Shape_i{1}.0, Shape_i{0}.0, Shape_i{1}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{1}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{1}.0, Shape_i{0}.0, Shape_i{1}.0, Shape_i{0}.0, Shape_i{1}.0, Shape_i{0}.0, Shape_i{1}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{0}.0, Shape_i{1}.0, Shape_i{0}.0, Shape_i{1}.0, Shape_i{0}.0, Alloc.0, Alloc.0)
Toposort index: 120
Inputs types: [TensorType(int64, scalar), TensorType(int64, 3D), TensorType(int64, 3D), TensorType(float64, vector), TensorType(float64, vector), TensorType(float64, 3D), TensorType(float64, 3D), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, 3D), TensorType(float64, 3D), TensorType(float64, 3D), TensorType(float64, 3D), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, vector), TensorType(float64, vector), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, vector), TensorType(float64, vector), TensorType(float64, vector), TensorType(int64, matrix), TensorType(int64, vector), TensorType(float64, matrix), TensorType(float64, 3D), TensorType(float64, matrix), TensorType(float64, 3D), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, scalar), TensorType(int64, matrix), TensorType(int64, vector)]
Inputs shapes: [(), (3, 4, 2), (3, 4, 2), (4,), (2,), (2, 9, 9), (2, 9, 9), (2, 4), (2, 9), (2, 9, 9), (2, 9, 9), (2, 9, 9), (2, 9, 9), (2, 9), (2, 9), (2, 9), (9, 9), (9, 9), (4,), (9,), (9, 9), (9, 9), (9, 9), (9, 9), (9,), (9,), (9,), (36, 11), (36,), (13, 10), (36, 11, 11), (36, 11), (36, 11, 11), (4, 4), (36, 11), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (36, 11), (36,)]
Inputs strides: [(), (64, 16, 8), (-64, 16, 8), (-8,), (8,), (648, 72, 8), (648, 72, 8), (32, 8), (72, 8), (648, 72, 8), (648, 72, 8), (648, 72, 8), (648, 72, 8), (72, 8), (72, 8), (72, 8), (72, 8), (72, 8), (8,), (8,), (72, 8), (72, 8), (72, 8), (72, 8), (8,), (8,), (8,), (88, 8), (8,), (80, 8), (968, 88, 8), (88, 8), (968, 88, 8), (32, 8), (88, 8), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (), (88, 8), (8,)]
Inputs values: [array(3), 'not shown', 'not shown', array([1., 0., 0., 0.]), array([ 0., nan]), 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', array([ 0.27957155,  0.17552981,  0.27293447, -0.19001233]), 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', array(11), array(36), array(4), array(4), array(11), array(11), array(36), array(11), array(36), array(11), array(11), array(36), array(10), array(13), array(36), array(11), array(36), array(9), array(9), array(9), array(9), array(9), array(9), array(9), array(9), array(9), array(9), array(9), array(4), array(9), array(9), array(9), array(9), 'not shown', 'not shown']
Outputs clients: [[], [Subtensor{int64}(forall_inplace,cpu,scan_fn&grad_of_scan_fn}.1, ScalarFromTensor.0)], [Subtensor{int64}(forall_inplace,cpu,scan_fn&grad_of_scan_fn}.2, ScalarFromTensor.0)], [Subtensor{int64}(forall_inplace,cpu,scan_fn&grad_of_scan_fn}.3, ScalarFromTensor.0)], [Subtensor{int64}(forall_inplace,cpu,scan_fn&grad_of_scan_fn}.4, ScalarFromTensor.0)], [Subtensor{int64}(forall_inplace,cpu,scan_fn&grad_of_scan_fn}.5, ScalarFromTensor.0)], [Subtensor{int64}(forall_inplace,cpu,scan_fn&grad_of_scan_fn}.6, ScalarFromTensor.0)], [Subtensor{int64}(forall_inplace,cpu,scan_fn&grad_of_scan_fn}.7, ScalarFromTensor.0)], [Subtensor{int64}(forall_inplace,cpu,scan_fn&grad_of_scan_fn}.8, ScalarFromTensor.0)], [Subtensor{int64}(forall_inplace,cpu,scan_fn&grad_of_scan_fn}.9, ScalarFromTensor.0)], [Subtensor{int64}(forall_inplace,cpu,scan_fn&grad_of_scan_fn}.10, ScalarFromTensor.0)], [Subtensor{int64}(forall_inplace,cpu,scan_fn&grad_of_scan_fn}.11, ScalarFromTensor.0)], [Subtensor{int64}(forall_inplace,cpu,scan_fn&grad_of_scan_fn}.12, ScalarFromTensor.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.

**Comment by SigProcess** [comment]
These are some of the files for reference. 
[typeAndTypeIDSavePath.txt](https://github.com/shuaiOKshuai/IPE/files/10487039/typeAndTypeIDSavePath.txt)

[typesFeatures.txt](https://github.com/shuaiOKshuai/IPE/files/10487043/typesFeatures.txt)


[nodesFeatures.txt](https://github.com/shuaiOKshuai/IPE/files/10487045/nodesFeatures.txt)

[subpathsSaveFile.txt](https://github.com/shuaiOKshuai/IPE/files/10487047/subpathsSaveFile.txt)


[sequencesSaveFile.txt](https://github.com/shuaiOKshuai/IPE/files/10487050/sequencesSaveFile.txt)

**Comment by shuaiOKshuai** [comment]
As far as I remember, the node features could be generated in two ways: 1. directly using the one-hot type information to serve as the node features; 2. using some approaches to generate the node embeddings (e.g., deepwalk) to serve as the node features. You can choose either of them depending on the dataset (or even combine them). Thus, these two kinds of features should be in the same format, i.e., the same format as your generated "nodesFeatures".

**Comment by SigProcess** [comment]
Hi, 
Thank you very much for taking the time to address this issue even though this is an older code. After I used the nodesFeatures and TypeFeatures in the same format, as you suggested, I was able to run the code fully with no errors. Thanks a lot again!
